### ISSUE TITLE
No background

### ISSUE THREAD

**Issue by nathunsmitty** [daily-bruin/interactive.2018.graduation-issue#5]
Getting the following error because `dist/` is in .gitignore. Please put the background image in `src/`! Parcel [should support images in both CSS and JS](https://parceljs.org/assets.html).
```
🚨  /Users/nathan/Developer/Daily Bruin/interactive.2018.graduation-issue/src/index.css:18:3: Cannot resolve dependency './../dist/bg.jpg' at '/Users/nathan/Dev  16 |   text-align: center;ve.2018.graduation-issue/dist/bg.jpg'
  17 |   margin: 0;
> 18 |   background-image: url('../dist/bg.jpg');
     |   ^
  19 |   background-size: cover;
  20 |   min-height: 100vh;
```

**Comment by dustinnewman98** [comment]
@nathunsmitty should we change the gitignore? not sure how else to resolve this cleanly

**Comment by nathunsmitty** [comment]
Just edited my above comment—parcel should be fine with images in src.

**Comment by dustinnewman98** [comment]
@nathunsmitty fixed!
